#!/bin/bash
link_src () {
	bot_retorno="$LINE\n"
	bot_retorno+=" 💥 Instalador Oficial 💥 \n 🧬 Soporte : Ubuntu 14.04 - 16.04 - 18.04 - 20.04 \n"
	bot_retorno+="Verifica tus Keys, : @Darinel \n"
	bot_retorno+="$LINE\n"
	bot_retorno+="sudo apt update -y; apt upgrade -y; wget https://raw.githubusercontent.com/DanssBot/genadminvps/master/GENERADOR-VPS-MX/instalscript.sh; chmod 777 instalscript.sh* && ./instalscript.sh*\n"
	bot_retorno+="$LINE\n"
msj_fun
}
